### ISSUE TITLE
Failed to load CRNN FP16 models with OpenCV 4.7 

### ISSUE THREAD

**Issue by fengyuentau** [opencv/opencv_zoo#122]
Reproducer:

```python
import cv2 as cv

cv.dnn.readNet("text_recognition_CRNN_CH_2022oct_fp16.onnx")
cv.dnn.readNet("text_recognition_CRNN_EN_2022oct_fp16.onnx")
```

Error log:

```
[ WARN:0@0.032] global onnx_graph_simplifier.cpp:804 getMatFromTensor DNN: load FP16 model as FP32 model, and it takes twice the FP16 RAM requirement.
[ERROR:0@0.049] global onnx_importer.cpp:1054 handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Conv]:(onnx_node!Conv_0) from domain='ai.onnx'
Traceback (most recent call last):
  File "/.../opencv_zoo/models/text_recognition_crnn/demo.py", line 63, in <module>
    recognizer = CRNN(modelPath=args.model)
  File "/.../opencv_zoo/models/text_recognition_crnn/crnn.py", line 16, in __init__
    self._model = cv.dnn.readNet(self._model_path)
cv2.error: OpenCV(4.7.0) /Users/opencv-cn/GHA-OCV-1/_work/opencv-python/opencv-python/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1073: error: (-2:Unspecified error) in function 'handleNode'
> Node [Conv@ai.onnx]:(onnx_node!Conv_0) parse error: OpenCV(4.7.0) /Users/opencv-cn/GHA-OCV-1/_work/opencv-python/opencv-python/opencv/modules/dnn/src/layers/convolution_layer.cpp:398: error: (-215:Assertion failed) inputs.size() != 0 in function 'getMemoryShapes'
>

[ WARN:0@0.024] global onnx_graph_simplifier.cpp:804 getMatFromTensor DNN: load FP16 model as FP32 model, and it takes twice the FP16 RAM requirement.
[ERROR:0@0.027] global onnx_importer.cpp:1054 handleNode DNN/ONNX: ERROR during processing node with 3 inputs and 1 outputs: [Conv]:(onnx_node!Conv_0) from domain='ai.onnx'
Traceback (most recent call last):
  File "/.../opencv_zoo/models/text_recognition_crnn/demo.py", line 63, in <module>
    recognizer = CRNN(modelPath=args.model)
  File "/.../opencv_zoo/models/text_recognition_crnn/crnn.py", line 16, in __init__
    self._model = cv.dnn.readNet(self._model_path)
cv2.error: OpenCV(4.7.0) /Users/opencv-cn/GHA-OCV-1/_work/opencv-python/opencv-python/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1073: error: (-2:Unspecified error) in function 'handleNode'
> Node [Conv@ai.onnx]:(onnx_node!Conv_0) parse error: OpenCV(4.7.0) /Users/opencv-cn/GHA-OCV-1/_work/opencv-python/opencv-python/opencv/modules/dnn/src/layers/convolution_layer.cpp:398: error: (-215:Assertion failed) inputs.size() != 0 in function 'getMemoryShapes'
>

```

**Comment by zihaomu** [comment]
@Charles-258, please take a look.

**Comment by Charles-258** [comment]
您好，我是王仡垚，您的邮件我已经收到，我会尽快回复。
