### ISSUE TITLE
Some models do not work with CANN backend

### ISSUE THREAD

**Issue by fengyuentau** [opencv/opencv_zoo#136]
List of models not working with CANN backend:

- [x] lpd_yunet
- [x] nanodet
- [x] mobilenet v2
- [x] pphumanseg
- [ ] dasiamrpn, cannot reproduce without the API, loading separately is good, not going to fix it.
- [x] handpose mp

Fixed by https://github.com/opencv/opencv/pull/23319 except DaSiamRPN.

The following models need to be updated:

- lpd_yunet, bump the opset version of Slice.
- pphumanseg, replace with an newer and simpler one.

Reproducer of lpd_yunet:

```shell
$ python3 benchmark.py --cfg config/license_plate_detection_yunet.yaml --fp32
Benchmarking LPD_YuNet with ['license_plate_detection_lpd_yunet_2022may.onnx']
Traceback (most recent call last):
  File "benchmark.py", line 143, in <module>
    benchmark.run(model)
  File "benchmark.py", line 103, in run
    self._benchmark_results[filename][str(size)] = self._metric.forward(model, *data[1:])
  File "/home/test_user01/fytao/opencv_zoo/benchmark/utils/metrics/detection.py", line 21, in forward
    model.infer(img)
  File "/home/test_user01/fytao/opencv_zoo/models/license_plate_detection_yunet/lpd_yunet.py", line 56, in infer
    outputBlob = self.model.forward(self.output_names)
cv2.error: OpenCV(4.7.0-dev) /home/test_user01/fytao/opencv-opencv/modules/dnn/src/layers/slice_layer.cpp:640: error: (-215:Assertion failed) sliceSteps.size() == 1 in function 'initCann'
```

Looks like the issue is the out-of-date Slice in the model (`starts` and `ends` are attributes, and no `steps`). Should have a try with upgrading opset version of lpd_yunet.

**Comment by fengyuentau** [comment]
NanoDet does not work as well with CANN backend:

```shell
$ python3 benchmark.py --cfg config/object_detection_nanodet.yaml --fp32
Benchmarking NanoDet with ['object_detection_nanodet_2022nov.onnx']
Traceback (most recent call last):
  File "benchmark.py", line 143, in <module>
    benchmark.run(model)
  File "benchmark.py", line 103, in run
    self._benchmark_results[filename][str(size)] = self._metric.forward(model, *data[1:])
  File "/home/test_user01/fytao/opencv_zoo/benchmark/utils/metrics/detection.py", line 21, in forward
    model.infer(img)
  File "/home/test_user01/fytao/opencv_zoo/models/object_detection_nanodet/nanodet.py", line 57, in infer
    outs = self.net.forward(self.net.getUnconnectedOutLayersNames())
cv2.error: OpenCV(4.7.0-dev) /home/test_user01/fytao/opencv-opencv/modules/dnn/src/layers/slice_layer.cpp:639: error: (-215:Assertion failed) sliceRanges.size() == 1 in function 'initCann'

```

It has `Split` operators which are parsed as `Slice` in dnn and it does not have `sliceRanges`.

**Comment by fengyuentau** [comment]
MobileNet V2 does not work as well:

```shell
$ python3 benchmark.py --cfg config/image_classification_mobilenet.yaml --fp32
Benchmarking MobileNet with ['image_classification_mobilenetv1_2022apr.onnx']
  image: coffee_mug.jpg
      [224, 224], latency (median): 5.1973 ms
  image: umbrella.jpg
      [224, 224], latency (median): 5.2358 ms
  image: wall_clock.jpg
      [224, 224], latency (median): 5.2185 ms
Benchmarking MobileNet with ['image_classification_mobilenetv2_2022apr.onnx']
[ERROR:0@22.642] global net_cann.cpp:291 compileCannGraph CANN graph check failed, ret = 1343266818
Traceback (most recent call last):
  File "benchmark.py", line 145, in <module>
    benchmark.run(model)
  File "benchmark.py", line 103, in run
    self._benchmark_results[filename][str(size)] = self._metric.forward(model, *data[1:])
  File "/home/test_user01/fytao/opencv_zoo/benchmark/utils/metrics/base.py", line 16, in forward
    model.infer(img)
  File "/home/test_user01/fytao/opencv_zoo/models/image_classification_mobilenet/mobilenet.py", line 57, in infer
    output_blob = self.model.forward(self.output_names)
cv2.error: OpenCV(4.7.0-dev) /home/test_user01/fytao/opencv-opencv/modules/dnn/src/net_cann.cpp:291: error: (-2:Unspecified error) CANN graph check failed in function 'compileCannGraph'

[ERROR:0@30.386] global net_cann.cpp:291 compileCannGraph CANN graph check failed, ret = 1343266818
Traceback (most recent call last):
  File "benchmark.py", line 145, in <module>
    benchmark.run(model)
  File "benchmark.py", line 103, in run
    self._benchmark_results[filename][str(size)] = self._metric.forward(model, *data[1:])
  File "/home/test_user01/fytao/opencv_zoo/benchmark/utils/metrics/base.py", line 16, in forward
    model.infer(img)
  File "/home/test_user01/fytao/opencv_zoo/models/image_classification_mobilenet/mobilenet.py", line 57, in infer
    output_blob = self.model.forward(self.output_names)
cv2.error: OpenCV(4.7.0-dev) /home/test_user01/fytao/opencv-opencv/modules/dnn/src/net_cann.cpp:291: error: (-2:Unspecified error) CANN graph check failed in function 'compileCannGraph'

[ERROR:0@32.648] global op_cann.cpp:258 loadToDevice CANN check failed, ret = 100000
Traceback (most recent call last):
  File "benchmark.py", line 145, in <module>
    benchmark.run(model)
  File "benchmark.py", line 103, in run
    self._benchmark_results[filename][str(size)] = self._metric.forward(model, *data[1:])
  File "/home/test_user01/fytao/opencv_zoo/benchmark/utils/metrics/base.py", line 16, in forward
    model.infer(img)
  File "/home/test_user01/fytao/opencv_zoo/models/image_classification_mobilenet/mobilenet.py", line 57, in infer
    output_blob = self.model.forward(self.output_names)
cv2.error: OpenCV(4.7.0-dev) /home/test_user01/fytao/opencv-opencv/modules/dnn/src/op_cann.cpp:258: error: (-2:Unspecified error) CANN check failed in function 'loadToDevice'
```

`ge_check_op.json`:

```
{
    "graph_id": 0,
    "op": [
        {
            "error_type": "infer_shape_error",
            "input0": {
                "data_type": "DT_FLOAT",
                "layout": "NCHW",
                "shape": [
                    1,
                    32,
                    112,
                    112
                ]
            },
            "input1": {
                "data_type": "DT_FLOAT",
                "layout": "NCHW",
                "shape": [
                    1
                ]
            },
            "input2": {
                "data_type": "DT_FLOAT",
                "layout": "ND",
                "shape": []
            },
            "name": "clip_2",
            "output0": {
                "data_type": "DT_FLOAT",
                "layout": "NCHW",
                "shape": []
            },
            "reason": "InferShapeFailed!",
            "type": "ClipByValue"
        }
    ],
    "session_id": 0
}
```

Something was wrong when building the model.

**Comment by fengyuentau** [comment]
DaSiamRPN:

```shell
$ python3 benchmark.py --cfg config/object_tracking_dasiamrpn.yaml --fp32
warmup and repeat in metric for tracking do not function.
Benchmarking DaSiamRPN with ['object_tracking_dasiamrpn_kernel_cls1_2021nov.onnx', 'object_tracking_dasiamrpn_kernel_r1_2021nov.onnx', 'object_tracking_dasiamrpn_model_2021nov.onnx']
FC from py: x format: NCHW
FC from py: w format: NCHW
FC from py: x format: NCHW
FC from py: w format: NCHW
FC from py: x format: NCHW
FC from py: w format: NCHW
FC from py: b format: NCHW
FC from py: y format: NCHW
FC from py: x format: NCHW
FC from py: w format: NCHW
FC from py: b format: NCHW
FC from py: y format: NCHW
FC from py: x format: NCHW
FC from py: w format: NCHW
FC from py: x format: NCHW
FC from py: w format: NCHW
[ERROR:0@7.816] global net_cann.cpp:291 compileCannGraph CANN graph check failed, ret = 1343266818
Traceback (most recent call last):
  File "benchmark.py", line 145, in <module>
    benchmark.run(model)
  File "benchmark.py", line 103, in run
    self._benchmark_results[filename][str(size)] = self._metric.forward(model, *data[1:])
  File "/home/test_user01/fytao/opencv_zoo/benchmark/utils/metrics/tracking.py", line 19, in forward
    model.init(first_frame, tuple(roi))
  File "/home/test_user01/fytao/opencv_zoo/models/object_tracking_dasiamrpn/dasiamrpn.py", line 52, in init
    self._model.init(image, roi)
cv2.error: OpenCV(4.7.0-dev) /home/test_user01/fytao/opencv-opencv/modules/dnn/src/net_cann.cpp:291: error: (-2:Unspecified error) CANN graph check failed in function 'compileCannGraph'

FC from py: x format: NCHW
FC from py: w format: NCHW
FC from py: x format: NCHW
FC from py: w format: NCHW
FC from py: x format: NCHW
FC from py: w format: NCHW
FC from py: b format: NCHW
FC from py: y format: NCHW
FC from py: x format: NCHW
FC from py: w format: NCHW
FC from py: b format: NCHW
FC from py: y format: NCHW
FC from py: x format: NCHW
FC from py: w format: NCHW
FC from py: x format: NCHW
FC from py: w format: NCHW
[ERROR:0@16.709] global net_cann.cpp:291 compileCannGraph CANN graph check failed, ret = 1343266818
Traceback (most recent call last):
  File "benchmark.py", line 145, in <module>
    benchmark.run(model)
  File "benchmark.py", line 103, in run
    self._benchmark_results[filename][str(size)] = self._metric.forward(model, *data[1:])
  File "/home/test_user01/fytao/opencv_zoo/benchmark/utils/metrics/tracking.py", line 19, in forward
    model.init(first_frame, tuple(roi))
  File "/home/test_user01/fytao/opencv_zoo/models/object_tracking_dasiamrpn/dasiamrpn.py", line 52, in init
    self._model.init(image, roi)
cv2.error: OpenCV(4.7.0-dev) /home/test_user01/fytao/opencv-opencv/modules/dnn/src/net_cann.cpp:291: error: (-2:Unspecified error) CANN graph check failed in function 'compileCannGraph'

[ERROR:0@19.213] global op_cann.cpp:258 loadToDevice CANN check failed, ret = 100000
Traceback (most recent call last):
  File "benchmark.py", line 145, in <module>
    benchmark.run(model)
  File "benchmark.py", line 103, in run
    self._benchmark_results[filename][str(size)] = self._metric.forward(model, *data[1:])
  File "/home/test_user01/fytao/opencv_zoo/benchmark/utils/metrics/tracking.py", line 19, in forward
    model.init(first_frame, tuple(roi))
  File "/home/test_user01/fytao/opencv_zoo/models/object_tracking_dasiamrpn/dasiamrpn.py", line 52, in init
    self._model.init(image, roi)
cv2.error: OpenCV(4.7.0-dev) /home/test_user01/fytao/opencv-opencv/modules/dnn/src/op_cann.cpp:258: error: (-2:Unspecified error) CANN check failed in function 'loadToDevice'
```

Reasons unknown.

**Comment by fengyuentau** [comment]
MP-HandPose:

```shell
$ python3 benchmark.py --cfg config/handpose_estimation_mediapipe.yaml --fp32
Benchmarking MPHandPose with ['handpose_estimation_mediapipe_2023feb.onnx']
[ERROR:0@5.412] global net_cann.cpp:291 compileCannGraph CANN graph check failed, ret = 1343266818
Traceback (most recent call last):
  File "benchmark.py", line 145, in <module>
    benchmark.run(model)
  File "benchmark.py", line 103, in run
    self._benchmark_results[filename][str(size)] = self._metric.forward(model, *data[1:])
  File "/home/test_user01/fytao/opencv_zoo/benchmark/utils/metrics/recognition.py", line 18, in forward
    model.infer(img, bbox)
  File "/home/test_user01/fytao/opencv_zoo/models/handpose_estimation_mediapipe/mp_handpose.py", line 111, in infer
    output_blob = self.model.forward(self.model.getUnconnectedOutLayersNames())
cv2.error: OpenCV(4.7.0-dev) /home/test_user01/fytao/opencv-opencv/modules/dnn/src/net_cann.cpp:291: error: (-2:Unspecified error) CANN graph check failed in function 'compileCannGraph'

[ERROR:0@12.889] global net_cann.cpp:291 compileCannGraph CANN graph check failed, ret = 1343266818
Traceback (most recent call last):
  File "benchmark.py", line 145, in <module>
    benchmark.run(model)
  File "benchmark.py", line 103, in run
    self._benchmark_results[filename][str(size)] = self._metric.forward(model, *data[1:])
  File "/home/test_user01/fytao/opencv_zoo/benchmark/utils/metrics/recognition.py", line 18, in forward
    model.infer(img, bbox)
  File "/home/test_user01/fytao/opencv_zoo/models/handpose_estimation_mediapipe/mp_handpose.py", line 111, in infer
    output_blob = self.model.forward(self.model.getUnconnectedOutLayersNames())
cv2.error: OpenCV(4.7.0-dev) /home/test_user01/fytao/opencv-opencv/modules/dnn/src/net_cann.cpp:291: error: (-2:Unspecified error) CANN graph check failed in function 'compileCannGraph'

[ERROR:0@15.185] global op_cann.cpp:258 loadToDevice CANN check failed, ret = 100000
Traceback (most recent call last):
  File "benchmark.py", line 145, in <module>
    benchmark.run(model)
  File "benchmark.py", line 103, in run
    self._benchmark_results[filename][str(size)] = self._metric.forward(model, *data[1:])
  File "/home/test_user01/fytao/opencv_zoo/benchmark/utils/metrics/recognition.py", line 18, in forward
    model.infer(img, bbox)
  File "/home/test_user01/fytao/opencv_zoo/models/handpose_estimation_mediapipe/mp_handpose.py", line 111, in infer
    output_blob = self.model.forward(self.model.getUnconnectedOutLayersNames())
cv2.error: OpenCV(4.7.0-dev) /home/test_user01/fytao/opencv-opencv/modules/dnn/src/op_cann.cpp:258: error: (-2:Unspecified error) CANN check failed in function 'loadToDevice'
```

ge_check_op.json:
```json
{
    "graph_id": 0,
    "op": [
        {
            "error_type": "infer_shape_error",
            "input0": {
                "data_type": "DT_FLOAT",
                "layout": "NCHW",
                "shape": [
                    1,
                    24,
                    112,
                    112
                ]
            },
            "input1": {
                "data_type": "DT_FLOAT",
                "layout": "NCHW",
                "shape": [
                    1
                ]
            },
            "input2": {
                "data_type": "DT_FLOAT",
                "layout": "ND",
                "shape": []
            },
            "name": "clip_3",
            "output0": {
                "data_type": "DT_FLOAT",
                "layout": "NCHW",
                "shape": []
            },
            "reason": "InferShapeFailed!",
            "type": "ClipByValue"
        }
    ],
    "session_id": 0
}
```
