### ISSUE TITLE
face_detection_yunet c++ demo builds but coredumps.

### ISSUE THREAD

**Issue by alamaral** [opencv/opencv_zoo#156]
I downloaded the latest OpenCV code yesterday, built and installed it on my Ubuntu 18.04 machine, then downloaded
the opencv_zoo code and built the face_detection_yunet demo.cpp code, unchanged, but when I run it it fails with the
following error:

$ ./demo
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.7.0-dev) /home/alamaral/src/opencv/modules/dnn/src/net_impl.cpp:275: error: (-204:Requested object was not found) Layer with requested id=-1 not found in function 'getLayerData'

Aborted (core dumped)

Anyone have any ideas as to what's going on?   One strange thing is that if I run the python demo with python2 it fails in exactly
the same way:
python demo.py 
Traceback (most recent call last):
  File "demo.py", line 136, in <module>
    results = model.infer(frame) # results is a tuple
  File "/home/alamaral/src/opencv_zoo/models/face_detection_yunet/yunet.py", line 54, in infer
    faces = self._model.detect(image)
cv2.error: OpenCV(4.7.0-dev) /home/alamaral/src/opencv/modules/dnn/src/net_impl.cpp:275: error: (-204:Requested object was not found) Layer with requested id=-1 not found in function 'getLayerData'

but running it with python3 it works fine.

**Comment by alamaral** [comment]
Is there any chance I could get a copy of the new YuNet data file?

**Comment by alamaral** [comment]
Would checking out the 4.7.0 tag in the opencv tree and rebuilding fix the problem?

**Comment by fengyuentau** [comment]
> Is there any chance I could get a copy of the new YuNet data file?

You can get it from https://github.com/opencv/opencv_zoo/pull/151. To be precise, visit https://github.com/Wwupup/opencv_zoo/blob/yunetv2/models/face_detection_yunet/face_detection_yunet_2023mar.onnx and click download.

> Would checking out the 4.7.0 tag in the opencv tree and rebuilding fix the problem?

Yes, it should.

**Comment by fengyuentau** [comment]
Closing for no response. Feel free to reopen if you have more questions.
